### ISSUE TITLE
Preprocess not firing

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/pwa#4]
@herbdool Correct me if I'm wrong but should `function pwa_preprocess_html` actually be `function pwa_preprocess_page`?

**Comment by herbdool** [comment]
I think you might be right @laryn. Do you want to submit a PR? I don't actually use this module so not putting in much time.

**Comment by laryn** [comment]
@herbdool I haven't used it before either but want to test it out a bit. PR here: 
https://github.com/backdrop-contrib/pwa/pull/5
